// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlocklistDB() {
  return window['go']['main']['App']['GetBlocklistDB']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetEndtimeDB() {
  return window['go']['main']['App']['GetEndtimeDB']();
}

export function SetBlocklistDB(arg1) {
  return window['go']['main']['App']['SetBlocklistDB'](arg1);
}

export function StartBlocker(arg1, arg2) {
  return window['go']['main']['App']['StartBlocker'](arg1, arg2);
}
