// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlocklistDB():Promise<Array<string>>;

export function GetDaemonRunningStatus():Promise<boolean>;

export function GetEndtimeDB():Promise<number>;

export function SetBlocklistDB(arg1:Array<string>):Promise<void>;

export function StartBlocker(arg1:number,arg2:Array<string>):Promise<number>;
