// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDaemonRunningStatus():Promise<boolean>;

export function GetEndTime(arg1:string):Promise<number>;

export function StartBlocker(arg1:number,arg2:Array<string>):Promise<number>;
