// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDaemonRunningStatus() {
  return window['go']['main']['App']['GetDaemonRunningStatus']();
}

export function GetEndTime(arg1) {
  return window['go']['main']['App']['GetEndTime'](arg1);
}

export function StartBlocker(arg1, arg2) {
  return window['go']['main']['App']['StartBlocker'](arg1, arg2);
}
