name: Create Release on Tag Push

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3 # Replace with your required Go version

      # Build for macOS
      - name: Build for macOS
        run: ./build/build_macos.sh
        env:
          GOOS: darwin
          GOARCH: amd64 # amd=intel, arm=apple silicon

      # Compress binaries
      - name: Zip binaries
        run: |
          mkdir -p release
          zip -r release/BetterBlockedThanSorry.app.zip build/bin/BetterBlockedThanSorry.app

      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload release assets
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/BetterBlockedThanSorry.app.zip
          asset_name: BetterBlockedThanSorry.app.zip
          asset_content_type: application/zip
